In [ ]:
import numpy as np
import pandas as pn

dataset = pn.read_csv('../data/iris.txt', sep=" ")

ModuleNotFoundError: No module named 'pandas'

In [2]:
dataset.head()

sl   sw   pl   pw  c
0  5.1  3.5  1.4  0.2  1
1  4.9  3.0  1.4  0.2  1
2  4.7  3.2  1.3  0.2  1
3  4.6  3.1  1.5  0.2  1
4  5.0  3.6  1.4  0.2  1

In [3]:
dataset

sl   sw   pl   pw  c
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  3
121  5.6  2.8  4.9  2.0  3
122  7.7  2.8  6.7  2.0  3
123  6.3  2.7  4.9  1.8  3
124  6.7  3.3  5.7  2.1  3
125  7.2  3.2  6.0  1.8  3
126  6.2  2.8  4.8  1.8  3
127  6.1  3.0  4.9  1.8  3
128  6.4  2.8  5.6  2.1  3
129  7.2  3.0  5.8  1.6  3
130  7.4  2.8  6.1  1.9  3
131  7.9  3.8  6.4  2.0  3
132  6.4  2.8  5.6  2.2  3
133  6.3  2.8  5.1  1.5  3
134  6.1  2.6  5.6  1.4  3
135  7.7  3.0  6.1  2.3  3
136  6.3  3.4  5.6  2.4  3
137  6.4  3.1  5.5  1.8  3
138  6.0  3.0  4.8  1.8  3
139  6.9  3.1  5.4  2.1  3
140  6.7  3.1  5.6  2.4  3
141  6.9  3.1  5.1  2.3  3
142  5.8  2.7  5.1  1.9  3
143  6.8  3.2  5.9  2.3  3
144  6.7  3.3  5.7  2.5  3
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [149]:
dataset.columns

Index(['sl', 'sw', 'pl', 'pw', 'c'], dtype='object')

In [4]:
target = 'c'
features = [c for c in dataset.columns if c != target]

In [151]:
features

['sl', 'sw', 'pl', 'pw']

In [5]:
dataset['c'] = ((dataset['c'] == 1) * 1) # if class!=setosa class==0

In [6]:
dataset

sl   sw   pl   pw  c
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  0
121  5.6  2.8  4.9  2.0  0
122  7.7  2.8  6.7  2.0  0
123  6.3  2.7  4.9  1.8  0
124  6.7  3.3  5.7  2.1  0
125  7.2  3.2  6.0  1.8  0
126  6.2  2.8  4.8  1.8  0
127  6.1  3.0  4.9  1.8  0
128  6.4  2.8  5.6  2.1  0
129  7.2  3.0  5.8  1.6  0
130  7.4  2.8  6.1  1.9  0
131  7.9  3.8  6.4  2.0  0
132  6.4  2.8  5.6  2.2  0
133  6.3  2.8  5.1  1.5  0
134  6.1  2.6  5.6  1.4  0
135  7.7  3.0  6.1  2.3  0
136  6.3  3.4  5.6  2.4  0
137  6.4  3.1  5.5  1.8  0
138  6.0  3.0  4.8  1.8  0
139  6.9  3.1  5.4  2.1  0
140  6.7  3.1  5.6  2.4  0
141  6.9  3.1  5.1  2.3  0
142  5.8  2.7  5.1  1.9  0
143  6.8  3.2  5.9  2.3  0
144  6.7  3.3  5.7  2.5  0
145  6.7  3.0  5.2  2.3  0
146  6.3  2.5  5.0  1.9  0
147  6.5  3.0  5.2  2.0  0
148  6.2  3.4  5.4  2.3  0
149  5.9  3.0  5.1  1.8  0

[150 rows x 5 columns]

In [157]:
x = dataset.iloc[:, :4].values

In [158]:
x

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [161]:
y = dataset.iloc[:, 4].values

In [162]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
y = dataset.iloc[:, 4].values
x = dataset.iloc[:, :4].values

#my test indices are first 10 and the last 20
test_indices = np.array(list(range(10)) + list(range(130,150)))
#set all of them to true
mask = np.ones(150,dtype=bool)
#except test_indices
mask[test_indices] = False

one_column = np.ones((150, 1))

x = np.concatenate((x, one_column), axis=1)

#inputs
X_train = x[mask, :]
X_test = x[~mask, :]

#expected output
y_train = y[mask]
y_test = y[~mask]

In [10]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X=X_train, y=y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
log_reg.predict(X_test), y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0]))

In [15]:
y_predictions = log_reg.predict_proba(X_test)
y_predictions

array([[  2.00700585e-02,   9.79929942e-01],
       [  4.22047284e-02,   9.57795272e-01],
       [  2.79805340e-02,   9.72019466e-01],
       [  5.05365605e-02,   9.49463439e-01],
       [  1.81429035e-02,   9.81857097e-01],
       [  2.42391069e-02,   9.75760893e-01],
       [  3.01345634e-02,   9.69865437e-01],
       [  2.94971229e-02,   9.70502877e-01],
       [  5.71327214e-02,   9.42867279e-01],
       [  4.15176037e-02,   9.58482396e-01],
       [  9.99742379e-01,   2.57620799e-04],
       [  9.99420953e-01,   5.79047176e-04],
       [  9.99597786e-01,   4.02214413e-04],
       [  9.97686970e-01,   2.31302997e-03],
       [  9.99399974e-01,   6.00026189e-04],
       [  9.99744260e-01,   2.55740056e-04],
       [  9.99266806e-01,   7.33194177e-04],
       [  9.98874911e-01,   1.12508903e-03],
       [  9.96056855e-01,   3.94314454e-03],
       [  9.98750516e-01,   1.24948393e-03],
       [  9.99441764e-01,   5.58236460e-04],
       [  9.98015484e-01,   1.98451641e-03],
       [  

In [17]:
from sklearn.metrics import log_loss

log_loss_score = log_loss(y_test, y_predictions)
log_loss_score

0.012389895298886122